spring.application.name=InventoryService
server.port=8082

spring.datasource.url=jdbc:sqlserver://KRISH\\SQLEXPRESS;databaseName=INTEGRATION;encrypt=true;trustServerCertificate=true;

spring.datasource.username=sa
spring.datasource.password=QWer1234#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

logging.level.org.springframework=INFO
